// Worker code generator that creates inline worker code from shared core logic
// This eliminates the maintenance nightmare of duplicating logic in string literals

// Import the actual functions to stringify them
import {
  mapSongToMidiTicksCore,
  getFirstPhases,
  reduceCollectorToMidiMap,
  createWorkerResult,
} from './shared/midiMappingCore'
import {
  getAllPhaseBarNotesWorker,
  getFollowingPhasesWorker,
  createWorkerMessageHandler,
} from './shared/workerUtils'
import { tickCounts } from './util/constantsUtil'
import { parseNoteTags, quantizeNote } from './worker-utils'

// Helper function to stringify a function
function stringifyFunction(fn: (...args: unknown[]) => unknown): string {
  return fn.toString()
}

// Helper function to get constants as a string
function getConstantsString(): string {
  return `
    // Constants (stringified from util/constantsUtil)
    const ppq = 128
    const BAR = 'bar'
    const tickCounts = ${JSON.stringify(tickCounts, null, 6)}
  `
}

// Generate the inline worker code by stringifying the actual functions
export function generateInlineWorkerCode(): string {
  // Stringify the actual functions to avoid duplication
  const parseNoteTagsStr = stringifyFunction(parseNoteTags)
  const quantizeNoteStr = stringifyFunction(quantizeNote)
  const getAllPhaseBarNotesWorkerStr = stringifyFunction(
    getAllPhaseBarNotesWorker
  )
  const getFollowingPhasesWorkerStr = stringifyFunction(
    getFollowingPhasesWorker
  )
  const mapSongToMidiTicksCoreStr = stringifyFunction(mapSongToMidiTicksCore)
  const getFirstPhasesStr = stringifyFunction(getFirstPhases)
  const reduceCollectorToMidiMapStr = stringifyFunction(
    reduceCollectorToMidiMap
  )
  const createWorkerResultStr = stringifyFunction(createWorkerResult)
  const createWorkerMessageHandlerStr = stringifyFunction(
    createWorkerMessageHandler
  )

  return `
    // Auto-generated inline Web Worker for mapSongToMidiTicks processing
    // This code is generated by stringifying the actual shared functions
    // Generated from: shared/midiMappingCore.ts, shared/workerUtils.ts, worker-utils.ts

    ${getConstantsString()}

    // Utility functions (stringified from worker-utils.ts)
    const parseNoteTags = ${parseNoteTagsStr}
    const quantizeNote = ${quantizeNoteStr}

    // Worker-specific implementations (stringified from shared/workerUtils.ts)
    const getAllPhaseBarNotesWorker = ${getAllPhaseBarNotesWorkerStr}
    const getFollowingPhasesWorker = ${getFollowingPhasesWorkerStr}

    // Core mapping function (stringified from shared/midiMappingCore.ts)
    const mapSongToMidiTicksCore = ${mapSongToMidiTicksCoreStr}

    // Utility functions (stringified from shared/midiMappingCore.ts)
    const getFirstPhases = ${getFirstPhasesStr}
    const reduceCollectorToMidiMap = ${reduceCollectorToMidiMapStr}
    const createWorkerResult = ${createWorkerResultStr}

    // Worker message handler utility (stringified from shared/workerUtils.ts)
    const createWorkerMessageHandler = ${createWorkerMessageHandlerStr}

    // Main worker function (adapted from shared/midiMappingCore.ts)
    function mapSongToMidiTicksWorker(phases, notesByBar) {
      const firstPhases = getFirstPhases(phases)
      const collector = []
      const phaseAndBarStartAndEndTicks = {
        phases: {},
        bars: {},
      }

      firstPhases.forEach(([phaseName, phase]) => {
        mapSongToMidiTicksCore(phaseName, phase, 0, collector, phaseAndBarStartAndEndTicks, getAllPhaseBarNotesWorker, getFollowingPhasesWorker)
      })

      // phase-level massaging here.
      const midiMap = reduceCollectorToMidiMap(collector)

      // Return serialized result (plain JS objects)
      return createWorkerResult(midiMap, phaseAndBarStartAndEndTicks)
    }

    // Worker message handler
    self.onmessage = createWorkerMessageHandler(mapSongToMidiTicksWorker)
  `
}

// Export a function that can be used to validate the generated code
export function validateWorkerCode(): boolean {
  try {
    // This function can be used to validate that the generated code is syntactically correct
    const code = generateInlineWorkerCode()
    // Basic validation - check that the code contains expected functions
    return (
      code.includes('mapSongToMidiTicksWorker') &&
      code.includes('mapSongToMidiTicksCore') &&
      code.includes('parseNoteTags') &&
      code.includes('quantizeNote') &&
      code.includes('getAllPhaseBarNotesWorker') &&
      code.includes('getFollowingPhasesWorker') &&
      code.includes('getFirstPhases') &&
      code.includes('reduceCollectorToMidiMap') &&
      code.includes('createWorkerResult') &&
      code.includes('createWorkerMessageHandler')
    )
  } catch (error) {
    console.error('Worker code validation failed:', error)
    return false
  }
}

// Export a function to get the source of the generated code for debugging
export function getWorkerCodeSource(): string {
  return `
    // Source functions used to generate worker code:
    // - parseNoteTags: ${parseNoteTags.toString().substring(0, 100)}...
    // - quantizeNote: ${quantizeNote.toString().substring(0, 100)}...
    // - getAllPhaseBarNotesWorker: ${getAllPhaseBarNotesWorker.toString().substring(0, 100)}...
    // - getFollowingPhasesWorker: ${getFollowingPhasesWorker.toString().substring(0, 100)}...
    // - mapSongToMidiTicksCore: ${mapSongToMidiTicksCore.toString().substring(0, 100)}...
    // - getFirstPhases: ${getFirstPhases.toString().substring(0, 100)}...
    // - reduceCollectorToMidiMap: ${reduceCollectorToMidiMap.toString().substring(0, 100)}...
    // - createWorkerResult: ${createWorkerResult.toString().substring(0, 100)}...
    // - createWorkerMessageHandler: ${createWorkerMessageHandler.toString().substring(0, 100)}...
    // - tickCounts: ${JSON.stringify(tickCounts)}
  `
}
