// Worker code generator that creates inline worker code from shared core logic
// This eliminates the maintenance nightmare of duplicating logic in string literals

// Import the actual functions to stringify them
import {
  mapSongToMidiTicksCore,
  mapPhaseTicksCore,
} from './shared/midiMappingCore'
import {
  getAllPhaseBarNotesWorker,
  getFollowingPhasesWorker,
  createWorkerMessageHandler,
} from './shared/workerUtils'
import { tickCounts } from './util/constantsUtil'
import {
  parseNoteTags,
  quantizeNote,
  peprnIsNum,
  isCsvArg,
  parseCsvArg,
  calcFractionalDelay,
  isFraction,
  calcTickDelay,
  quantizeOffset,
} from './worker-utils'

// Helper function to stringify a function
function stringifyFunction(fn: (...args: unknown[]) => unknown): string {
  return fn.toString()
}

// Helper function to get constants as a string
function getConstantsString(): string {
  return `
    // Constants (stringified from util/constantsUtil)
    const ppq = 128
    const BAR = 'bar'
    const tickCounts = ${JSON.stringify(tickCounts, null, 6)}
  `
}

// Generate the inline worker code by stringifying the actual functions
export function generateInlineWorkerCode(): string {
  try {
    // Stringify the actual functions to avoid duplication
    const parseNoteTagsStr = stringifyFunction(parseNoteTags)
    const quantizeNoteStr = stringifyFunction(quantizeNote)
    const peprnIsNumStr = stringifyFunction(peprnIsNum)
    const isCsvArgStr = stringifyFunction(isCsvArg)
    const parseCsvArgStr = stringifyFunction(parseCsvArg)
    const calcFractionalDelayStr = stringifyFunction(calcFractionalDelay)
    const isFractionStr = stringifyFunction(isFraction)
    const calcTickDelayStr = stringifyFunction(calcTickDelay)
    const quantizeOffsetStr = stringifyFunction(quantizeOffset)
    const getAllPhaseBarNotesWorkerStr = stringifyFunction(
      getAllPhaseBarNotesWorker
    )
    const getFollowingPhasesWorkerStr = stringifyFunction(
      getFollowingPhasesWorker
    )
    const mapSongToMidiTicksCoreStr = stringifyFunction(mapSongToMidiTicksCore)
    const mapPhaseTicksCoreStr = stringifyFunction(mapPhaseTicksCore)
    const createWorkerMessageHandlerStr = stringifyFunction(
      createWorkerMessageHandler
    )

    return `
    // Auto-generated inline Web Worker for mapSongToMidiTicks processing
    // This code is generated by stringifying the actual shared functions
    // Generated from: shared/midiMappingCore.ts, shared/workerUtils.ts, worker-utils.ts

    ${getConstantsString()}

    // Utility functions (stringified from worker-utils.ts)
    const parseNoteTags = ${parseNoteTagsStr}
    const quantizeNote = ${quantizeNoteStr}

    // Worker-specific implementations (stringified from shared/workerUtils.ts)
    // Helper functions (stringified from worker-utils.ts)
    const peprnIsNum = ${peprnIsNumStr}
    const isCsvArg = ${isCsvArgStr}
    const parseCsvArg = ${parseCsvArgStr}
    const calcFractionalDelay = ${calcFractionalDelayStr}
    const isFraction = ${isFractionStr}
    const calcTickDelay = ${calcTickDelayStr}
    const quantizeOffset = ${quantizeOffsetStr}

    const getAllPhaseBarNotesWorker = ${getAllPhaseBarNotesWorkerStr}
    const getFollowingPhasesWorker = ${getFollowingPhasesWorkerStr}

    // Core mapping functions (stringified from shared/midiMappingCore.ts)
    const mapPhaseTicksCore = ${mapPhaseTicksCoreStr}
    const mapSongToMidiTicksCore = ${mapSongToMidiTicksCoreStr}

    // Worker message handler utility (stringified from shared/workerUtils.ts)
    const createWorkerMessageHandler = ${createWorkerMessageHandlerStr}

    // Create wrapper functions that capture the notesByBar and phases parameters
    function createGetAllPhaseBarNotesWrapper(notesByBar) {
      return function(phaseName) {
        return getAllPhaseBarNotesWorker(phaseName, notesByBar)
      }
    }

    function createGetFollowingPhasesWrapper(phases) {
      return function(phaseName) {
        return getFollowingPhasesWorker(phaseName, phases)
      }
    }

    // Main worker function (adapted from shared/midiMappingCore.ts)
    function mapSongToMidiTicksWorker(phases, notesByBar) {
      // Create wrapper functions that capture the parameters
      const getAllPhaseBarNotes = createGetAllPhaseBarNotesWrapper(notesByBar)
      const getFollowingPhases = createGetFollowingPhasesWrapper(phases)

      // Use the shared core function directly with dependencies
      return mapSongToMidiTicksCore(phases, notesByBar, getAllPhaseBarNotes, getFollowingPhases, tickCounts, parseNoteTags, quantizeNote)
    }

    // Worker message handler
    self.onmessage = createWorkerMessageHandler(mapSongToMidiTicksWorker)
  `
  } catch (error) {
    console.error('Failed to generate worker code:', error)
    throw new Error(
      `Worker code generation failed: ${error instanceof Error ? error.message : 'Unknown error'}`
    )
  }
}

// Export a function that can be used to validate the generated code
export function validateWorkerCode(): boolean {
  try {
    // This function can be used to validate that the generated code is syntactically correct
    const code = generateInlineWorkerCode()
    // Basic validation - check that the code contains expected functions
    return (
      code.includes('mapSongToMidiTicksWorker') &&
      code.includes('mapSongToMidiTicksCore') &&
      code.includes('mapPhaseTicksCore') &&
      code.includes('parseNoteTags') &&
      code.includes('quantizeNote') &&
      code.includes('getAllPhaseBarNotesWorker') &&
      code.includes('getFollowingPhasesWorker') &&
      code.includes('createWorkerMessageHandler')
    )
  } catch (error) {
    console.error('Worker code validation failed:', error)
    return false
  }
}

// Export a function to get the source of the generated code for debugging
export function getWorkerCodeSource(): string {
  return `
    // Source functions used to generate worker code:
    // - parseNoteTags: ${parseNoteTags.toString().substring(0, 100)}...
    // - quantizeNote: ${quantizeNote.toString().substring(0, 100)}...
    // - getAllPhaseBarNotesWorker: ${getAllPhaseBarNotesWorker.toString().substring(0, 100)}...
    // - getFollowingPhasesWorker: ${getFollowingPhasesWorker.toString().substring(0, 100)}...
    // - mapPhaseTicksCore: ${mapPhaseTicksCore.toString().substring(0, 100)}...
    // - mapSongToMidiTicksCore: ${mapSongToMidiTicksCore.toString().substring(0, 100)}...
    // - createWorkerMessageHandler: ${createWorkerMessageHandler.toString().substring(0, 100)}...
    // - tickCounts: ${JSON.stringify(tickCounts)}
  `
}
